version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        MYSQL_USER: ${MYSQL_USER:-app}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "443:443"
    depends_on:
      - db

volumes:
  db_data:
