ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context

=== Business Context
[plantuml,"Deployment diagram",png]
----
@startuml
actor Player as user
actor "External Developers" as developers
component WebApp [
  <<System>>
  Web game
]

component PlayerService [
  <<System>>
  Player Management
]

component QuestionService [
  <<System>>
  Question Management
]

component WikiData [
    <<extern>>
    Wikidata
]

user ...> WebApp: Plays
WebApp ---> PlayerService : Handles\nlogin and signup
WebApp -left-> QuestionService : Retrieves generated\nquestions for game
WebApp <-- WikiData : Retrieves\nInformation to\nform questions\nand answers
developers .right.> PlayerService : Modify\nplayer data
developers <.right. PlayerService : Retrieve\nplayer data
developers .right.> QuestionService : Modify questions
developers <.right. QuestionService : Retrieve question list
@enduml

----
* **Player:** Represents users who interact with the application to play games or view their history.
* **Question management:** The sytem that retrieves the questions generated from Wikidata.
* **Player management:** The system that manages player data, such as registration, login, and game history.
* **WikiData:** Component used to retrieve data from Wikidata and automatically generate questions.
* **External Developers:** Represents developers who access the system to retrieve player and question data.

=== Technical Context

[plantuml,"Technical Context Diagram",png]
----
actor Player as user
actor "External Developers" as developers
component WebApp [
  <<System>>
  Web game
]

component PlayerService [
  <<System>>
  PlayerService
]

component QuestionService [
  <<System>>
  QuestionService
]

component WikiData [
    <<extern>>
    Wikidata
]

component QuestionGenerator [
    <<system>>
    QuestionGenerator
]

component RestApiService [
    <<system>>
    RestApiService
]

database Database [
    Database
]

user .left.> WebApp: HTTPS
WebApp ---> PlayerService : Handles\nlogin, signup\nand game history
WebApp -left-> QuestionService : Retrieves generated\nquestions for game
QuestionGenerator <-up- WikiData : Get entity info\nfrom SPARQL HTTP
QuestionGenerator --> QuestionService : Generate questions\nwith entity data
QuestionService --> Database: Save\nquestion\nentities
QuestionService <-- Database: Retrieve\nsaved\nquestions
developers .up---.> RestApiService : HTTP\nPOST\nPUT\nDELETE
developers <.up. RestApiService : HTTP GET
RestApiService -up-> QuestionService: Retrieve/Modify questions
RestApiService ---> PlayerService: Retrieve/Modify player data

----

* **Player:** Represents users who interact with the application to play games or view their history.
* **Question service:** The system that retrieves the questions generated from Wikidata.
* **Player service:** The system that manages player data, such as registration, login, and game history.
* **WikiData:** Component used to retrieve data from Wikidata
* **Question generator:** The system that generates questions based on the data retrieved from Wikidata.
* **External Developers:** Represents developers who access the system to retrieve player and question data.
* **Database:** The database that stores player data, game history, and questions.
* **Rest API Service:** The service that provides an API for external developers to access player and question data.

==== Input/Output Mapping Table

[options="header",cols="1,2,2"]
|===
|Component|Input/Output|Channel/Protocol
| RestApiService| External developer interactions| HTTPS
| Frontend| User interactions, game display| HTTPS
| Database| User data, game history, questions| Specific database driver
| WikiData| Data for question generation| HTTP
| Question Generator| Generated questions| In-memory
| Question Service| Questions for game| In-memory
| Player Service| Player data| In-memory
|===