ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context


[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

[plantuml,"Deployment diagram",png]
----
  actor user
  component System[        
    <<System>>                 
    QuestionGame
  ]
  component WikiData
  database Database

  user --> System
  System --> Database
  System --> WikiData
----

**Explanation:**
* **User:** Represents users who interact with the application to play games or view their history.
* **System (QuestionGame):** The main system that hosts the game logic and manages user interactions.
* **WikiData:** Component used to retrieve data from Wikidata and automatically generate questions.
* **Database:** Stores system information, such as user data, generated questions, game history, etc.

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

[plantuml,"Technical Context Diagram",png]
----

  actor user
  actor developer
  database Database

  node "Question Generation"{
    [WikiData]
  }

  node "User Agent" {
    [Web / Mobile]
  }
  
  node "QuestionGame server" {
    [Frontend]
    [QuestionGame]
    [User's API]
    [Question's API]
  }
  
  user --> [Web / Mobile]
  [Web / Mobile] --> (Frontend): HTTPS
  [Frontend] --> (QuestionGame): To decide
  [QuestionGame] --> Database: Specific driver
  [QuestionGame] --> WikiData: HTTP
  [QuestionGame] <-- (User's API): To decide
  [QuestionGame] <-- (Question's API): To decide
  developer --> (User's API) : HTTPS
  developer --> (Question's API) : HTTPS
----
* User Agent: Represents the web or mobile interface used by users.
* QuestionGame server: The server-side components, including the Frontend, QuestionGame logic, User's API, and Question's API.
* HTTPS: Represents the communication channels, with HTTPS being the protocol used for secure communication.
* Question Generation: Represents the means used for question and answers generation.
* Database: Represents whichever system used for data persistence.
* To be decided: Indicates that specific details about the channels and protocols are yet to be determined.

==== Input/Output Mapping Table

[options="header",cols="1,2,2"]
|===
|Component|Input/Output|Channel/Protocol
| User's API| User registration, game history| HTTPS
| Question's API| Question data retrieval| HTTPS
| Frontend| User interactions, game display| HTTPS
| Database| User data, game history, questions| Specific database driver
| WikiData| Data for question generation| HTTP
|===