ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context

=== Business Context
[plantuml,"Deployment diagram",png]
----
@startuml
actor Player as user
actor "External Developers" as developers
component System [
  <<System>>
  QuestionGame
]
component WikiData as wikidata

user -down-> System : Uses
System -left-> wikidata : Retrieves\nInformation to\nform questions\nand answers
developers -down-> System : Asks for Player\n& Question Data
System -----> developers : Provides\nPlayer &\n Question Data
@enduml

----
* **Player:** Represents users who interact with the application to play games or view their history.
* **System (QuestionGame):** The main system that hosts the game logic and manages user interactions.
* **WikiData:** Component used to retrieve data from Wikidata and automatically generate questions.
* **Database:** Stores system information, such as user data, generated questions, game history, etc.
* **External Developers:** Represents developers who access the system's REST API to retrieve player and question data.

=== Technical Context

[plantuml,"Technical Context Diagram",png]
----
  actor user
  person developer
  database Database
  cloud WikiData


  node "User Agent"
  
  node "QuestionGame server"
  
  user --> [User Agent]
  [User Agent] --> [QuestionGame server]: HTTPS

  [QuestionGame server] --> Database: Specific driver
  [QuestionGame server] --> WikiData: HTTP
  developer --> [QuestionGame server] : HTTPS
----

* **User Agent:** Represents the web or mobile interface used by users.
* **QuestionGame server:** The server-side components, including the Frontend, QuestionGame logic, User's API, and Question's API.
* **HTTPS:** Represents the communication channels, with HTTPS being the protocol used for secure communication.
* **Question Generation:** Represents the means used for question and answers generation.
* **Database:** Represents whichever system used for data persistence.

==== Input/Output Mapping Table

[options="header",cols="1,2,2"]
|===
|Component|Input/Output|Channel/Protocol
| User's API| User registration, game history| HTTPS
| Question's API| Question data retrieval| HTTPS
| Frontend| User interactions, game display| HTTPS
| Database| User data, game history, questions| Specific database driver
| WikiData| Data for question generation| HTTP
|===