ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****

El propósito de esta sección es crear una lista ordenada de decisiones arquitectónicas que iremos tomando a medida que desarrollamos el proyecto. Esta lista irá ordenada en función de la importancia que tenga la decisión.

1. *Protección de la rama master*: Esta decisión fue tomada al comienzo de la primera reunión de equipo. Sin duda, esta es la decisión arquitectónica más importante, ya que significará no poder modificar la rama master sin que todos los miembros hayan revisado previamente las modificaciones, para que no se añada nada que pueda afectar el funcionamiento de la rama principal. Además de esto, también se creó la rama develop, que funcionará como una rama main2.0 para ir añadiendo los progresos que se vayan haciendo. Para añadir a esta rama también es necesaria la aprobación de algunos miembros del equipo.
2. *Cambio de JavaScript a Java con Spring*: Esta es una decisión que tomamos el martes 6 de febrero, después de la segunda sesión. Por lo que llevamos de proyecto, es una de las decisiones más importantes hasta ahora, ya que significará no emplear el proyecto base y empezar otra aplicación en otro lenguaje de programación. Hemos llegado a tomar esta decisión ya que consideramos mucho más accesible emplear el lenguaje Java, al ser este enseñado desde el principio de la carrera. Además, con lo que aprendemos en la asignatura SDI (Sistemas Distribuidos e Internet) podemos aplicarlo todo al desarrollo web, empleando el framework Spring. También hemos encontrado una librería en Java con la que podremos utilizar Wikidata muy fácilmente. Fue una decisión unánime que nos facilitará la fluidez de trabajo a largo plazo.