ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****

The purpose of this section is to create an ordered list of architectural decisions that we will make as we develop the project. This list will be ordered according to the importance of the decision.

1. *Protection of the master branch: This decision was made at the beginning of the first team meeting. Without a doubt, this is the most important architectural decision, as it will mean not being able to modify the master branch without all members having previously reviewed the modifications, so that nothing is added that could affect the functioning of the main branch. In addition to this, a develop branch was also created, which will function as a main2.0 branch for adding progress as it is made. To add to this branch also requires the approval of some members of the team.
2. *Switch from JavaScript to Java with Spring: This is a decision we made on Tuesday, February 6th, after the second session. So far in the project, it is one of the most important decisions so far, as it will mean not using the base project and starting another application in another programming language. We have come to this decision because we consider it much more accessible to use the Java language, as it has been taught from the beginning of the course. Moreover, with what we learn in the subject SDI we can apply it all to web development, using the Spring framework. We have also found a