ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****

_Nota: Los puntos (1), (2), (3) de la siguiente tabla repiten los requisitos de calidad de nivel superior del capítulo 1.2._

[cols="4", options="header"]
|===
|Quality category |Quality |Description |Scenario

|Usability
|Ease of use
|The application shall be easy to use by the user, with intuitive functionality.
|SC1

|
|Familiarity of the environment (2)
|The application should appeal to all fans of the original programme and provide a wide variety of questions.
|

|Performance
|Accuracy
|The questions in the application must be accurate, both the question and the correct answer.
|

|
|Efficiency (1)
|Accessing, creating questions and moving between questions should be fast to ensure user satisfaction.
|

|
|Robustness
|The system shall function reliably in all specified environments and operating conditions.
|SC2

|Safety
|Integrity
|The application shall be user-friendly, with intuitive functionality.
|

|Maintainability and support
|Maintenance (2)
|The application shall ensure that it can be easily extended and modified to provide new features to users.
|

|Cultural and Regional
|Multilingual
|The user interface texts must be able to be converted by a translation file into different languages with an ASCII character set.
|SC3
|===

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

[cols="2", options="header"]
|===
|Identification |Scenario

|SC1
|A user who is not familiar with the application will know how to use it after a few minutes of instruction.

|SC2
|The application should be able to be run from any device, from a computer to a mobile phone, without losing formatting.

|CS3
|With the appropriate translation files replacing the default language (English), all displayed and printed texts now appear in this language.
|===