ifndef::imagesdir[:imagesdir: ../images]

[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.



.Further Information

See https://docs.arc42.org/section-11/[Risks and Technical Debt] in the arc42 documentation.

****

[cols="1,2,3a", options="header"]
|===
| Priority | Risk/Debt | Description

| High | Migration to Java | Migration from the current project language, JavaScript (JS), to Java
| Medium | IDE Configuration | Version compatibility, extensions and other preferences to work perfectly without conflicts
| Medium | Database | Discuss which database is best for the project 
| Low | Docker  | Know how docker works, what it is for, how it is used and what its alternatives could be.
| Low | Microservices | Research about microservices and what they can contribute to the project


|===
